### ISSUE TITLE
Error: zlib@1.0.5 preinstall: `node-waf clean || true; node-waf configure build`

### ISSUE THREAD

**Issue by varunverma23** [kkaefer/node-zlib#16]
I am getting error while installing anything using npm.

21783 verbose stack Error: zlib@1.0.5 preinstall: `node-waf clean || true; node-waf configure build`
21783 verbose stack spawn ENOENT
21783 verbose stack     at ChildProcess.<anonymous> (/usr/local/Cellar/node@6/6.16.0/lib/node_modules/npm/lib/utils/spawn.js:33:16)
21783 verbose stack     at emitTwo (events.js:106:13)
21783 verbose stack     at ChildProcess.emit (events.js:191:7)
21783 verbose stack     at maybeClose (internal/child_process.js:920:16)
21783 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
21784 verbose pkgid zlib@1.0.5

**Comment by kebabmamedov** [comment]
same :/
